import type { Metadata } from "next";
import SecondNav from "../components/Child Components/Nav Components/SecondNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full h-screen bg-gray-400">
      <SecondNav />

      {children}
    </div>
  );
}
